### ISSUE TITLE
misconfigured package.json

### ISSUE THREAD

**Issue by janwirth** [SE7ENSKY/jade2php#2]
<code>
coffee> require './node_modules/jade2php/src/jade2php'</code>
<code>[Function]</code>

<code>coffee> require 'jade2php' </code>
<code>Error: Cannot find module 'jade2php'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at sandbox.require._require (/usr/lib/coffee-script/lib/coffee-script/coffee-script.js:121:25)
    at evalmachine.<anonymous>:3:5
    at Object.exports.eval (/usr/lib/coffee-script/lib/coffee-script/coffee-script.js:146:17)
    at Interface.run (/usr/lib/coffee-script/lib/coffee-script/repl.js:145:41)
    at Interface.EventEmitter.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:760:14)
</code>

require calls that do not specify the exact jade2php path will fail.

the entry point needs to be adjusted in the package.json file and a main js needs to be created.

**Comment by FranzSkuffka** [comment]
i was talking bogus right there. don't know what went wrong..

**Comment by FranzSkuffka** [comment]
I was talking crap right there.
however http://package-json-validator.com/ still throws 2 errors and some warnings.

**Comment by janwirth** [comment]
solved
SHA: 82dd70490ebe899cfedb68d261f33267d10d488a

**Comment by janwirth** [comment]
i made a mistake, in fact, defining a main entry point without coffee or js extension is the way to go. pull requests incoming.

**Comment by janwirth** [comment]
so require calls still don't work.
